### ISSUE TITLE
What are headers and how to get them

### ISSUE THREAD

**Issue by WojtexUU** [Tsugumik/shindenpl-master#1]
Hello, I wrote a python script to download videos from cda and now I want to combine them with your script but I have no idea what are headers and how to get them.

**Comment by Tsugumik** [comment]
Hi, I forgot about this script completely, I have an improved version of it somewhere on my computer, but I forgot to put it on github. To answer the question, headersapp - these are the frontend connection request headers, and the headersapi (connection to shindenapi is after selecting the player) - are the shinden api connection request headers. You can find them by going to shinden.pl from your browser in the "network" tab in developer tools.

The headers are to inform the server with which client (browser) to act and what response this client expects. In the case of this script, you need to send the request headers directly informing that we are requesting the page in Polish, otherwise server will reject the request because shinden.pl is blocked outside of Poland.

I think the general stuff about headers is well explained [here](https://developer.mozilla.org/en-US/docs/Glossary/Request_header)

Here's an example of where you can find the headers.
![image](https://user-images.githubusercontent.com/59662074/149843544-afeb447d-3da7-4eb5-ba33-a9878d68ce11.png)

Shinden.pl is very strange, I think it is worth working on the scraper for their website by yourself. You can learn a lot ... e.g. how not to make websites :)

**Comment by Tsugumik** [comment]
If you need any help I can write / call on Discord.

**Comment by WojtexUU** [comment]
Its still showing: Exception: Wrong headersapi or wrong episode number! I'm using example from readme and I have changed headersapp and headersapi for my own. On discord I'm Losif-kun#8141
